version: '3.3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        entrypoint: ["python", "app.py"]
        environment:
            DATABASE_URL: postgres://POSTGRES_DB@POSTGRES_USER/POSTGRES_PASSWORD
        depends_on:
            - postgres
    postgres:
        restart: always
        build: 
                context: .
                dockerfile: "Dockerfile-postgis"
        environment:
                - "POSTGRES_DB=${POSTGRES_DB}"
                - "POSTGRES_USER=${POSTGRES_USER}"
                - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        volumes:
                - ./database:/var/lib/postgresql
        ports:
                - 5432:5432
