#Start with postgis image
FROM mdillon/postgis as postgis_stg
#create load directory and copy shapefile
RUN mkdir tl_2019_us_state
COPY tl_2019_us_state/* /tl_2019_us_state/
RUN chmod 644 /tl_2019_us_state/* 
#COPY load script to /docker-entrypoint-initdb.d/
COPY z_load-shp_file.sh /docker-entrypoint-initdb.d/
